// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restauracja.Data;

namespace Restauracja.Migrations
{
    [DbContext(typeof(RestDbContext))]
    partial class RestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Restauracja.Models.Klient", b =>
                {
                    b.Property<int>("KlientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("NumerStolika")
                        .HasColumnType("int");

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.HasKey("KlientId");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("Restauracja.Models.PozycjaZamowienia", b =>
                {
                    b.Property<int>("IdPozycji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdPozycji");

                    b.ToTable("PozycjeZamowienia");
                });

            modelBuilder.Entity("Restauracja.Models.Zamowienie_PozycjaZamowienia", b =>
                {
                    b.Property<int>("IdZamownie")
                        .HasColumnType("int");

                    b.Property<int>("IdPozycji")
                        .HasColumnType("int");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Liczba")
                        .HasColumnType("int");

                    b.HasKey("IdZamownie", "IdPozycji");

                    b.HasIndex("IdPozycji");

                    b.ToTable("Zamowienie_PozycjaZamowienia");
                });

            modelBuilder.Entity("Restauracja.Models.Zamownie", b =>
                {
                    b.Property<int>("IdZamownie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.HasKey("IdZamownie");

                    b.HasIndex("KlientId");

                    b.ToTable("Zamownia");
                });

            modelBuilder.Entity("Restauracja.Models.Zamowienie_PozycjaZamowienia", b =>
                {
                    b.HasOne("Restauracja.Models.PozycjaZamowienia", "PozycjaZamowienia")
                        .WithMany("Zamowienie_PozycjaZamowienias")
                        .HasForeignKey("IdPozycji")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restauracja.Models.Zamownie", "Zamownie")
                        .WithMany("Zamowienie_PozycjaZamowienias")
                        .HasForeignKey("IdZamownie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PozycjaZamowienia");

                    b.Navigation("Zamownie");
                });

            modelBuilder.Entity("Restauracja.Models.Zamownie", b =>
                {
                    b.HasOne("Restauracja.Models.Klient", null)
                        .WithMany("Zamownies")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restauracja.Models.Klient", b =>
                {
                    b.Navigation("Zamownies");
                });

            modelBuilder.Entity("Restauracja.Models.PozycjaZamowienia", b =>
                {
                    b.Navigation("Zamowienie_PozycjaZamowienias");
                });

            modelBuilder.Entity("Restauracja.Models.Zamownie", b =>
                {
                    b.Navigation("Zamowienie_PozycjaZamowienias");
                });
#pragma warning restore 612, 618
        }
    }
}
